### PR TITLE
Add init implementation DynamoDB

### PR DESCRIPTION
**Pull request by LeonardoSouza97**
- I added the pageSize field in the standard fields.
- I started to implement DynamoDB, GET, POST, PUT, DELETE, GET ALL.
- GET ALL added filters like Like in Query Params (can do with more than one property)
- Added pagination

To do the tests you need to enter the information in the AWS environment variables:

**- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_REGION**

And create a table with the appropriate fields.

Obs: So far the "primary key" to search for is with the UUID field

### CODE REVIEW

**Comment by taciomedeiros** [comment]
Leonardo Thanks for the Pull Request. I will review in the next days. Could you add more information about the changes in the description?

**Comment by taciomedeiros** [comment]
@LeonardoSouza97 Could you remove the files from the compiled folders please!

**Comment by LeonardoSouza97** [comment]
> @LeonardoSouza97 Could you remove the files from the compiled folders please!

Updated! @taciomedeiros 

Thanks

**Comment by LeonardoSouza97** [comment]
- Add LastEvaluatedKey in response
- Add ExclusiveStartKey in query param
- Limit Page Size

**Pull request merged**
